codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: '85...100'

  parsers:
    javascript:
      enable_partials: yes

  status:
    project:
      default:
        target: 85
        threshold: null
        base: auto
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: null
        paths: null

    patch:
      default:
        target: 50
        threshold: null
        base: auto
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: null
        paths: null

    changes: no

comment:
  layout: 'reach, diff, flags, files, footer'
  behavior: default
  require_changes: no
